---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: k8smetricalarms.containerinsights.eks.com
spec:
  group: containerinsights.eks.com
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    kind: K8sMetricAlarm
    plural: k8smetricalarms
    singular: k8smetricalarm
    shortNames:
      - k8sma
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            minReplicas:
              type: integer
            maxReplicas:
              type: integer
            scaleUpBehavior:
              type: object
              properties:
                coolDown:
                  type: integer                
                policies:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      value:
                        type: integer
            scaleDownBehavior:
              type: object
              properties:
                coolDown:
                  type: integer
                policies:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      value:
                        type: integer
            deployment:
              type: string
            scaleUpAlarmConfig:
              type: string
            scaleDownAlarmConfig:
              type: string