---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudwatchalarm-controller-role
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: cloudwatchalarm-controller
rules:
- apiGroups:
  - containerinsights.eks.com
  resources:
  - k8smetricalarms
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudwatchalarm-controller-rolebinding
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: cloudwatchalarm-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudwatchalarm-controller-role
subjects:
- kind: ServiceAccount
  name: cloudwatchalarm-controller
  namespace: kube-system