---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: lambda-client-role
rules:
- apiGroups:
  - containerinsights.eks.com
  resources:
  - cloudwatchalarms
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - '*'

---  
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: lambda-client-rolebinding
roleRef:
  kind: ClusterRole
  name: lambda-client-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: lambda-client
    apiGroup: rbac.authorization.k8s.io


